config {
  type: "view",
  schema: "covid19",
  name: "tokyo",
  description: "東京の感染状況",
  columns: {
    date: "日",
    new_confirmed_count: "新規感染者数",
    new_deceased_count: "新規死者数"
  }
}

SELECT
  date,
  SUM(new_confirmed) AS new_confirmed_count,
  SUM(new_deceased) AS new_deceased_count
FROM
  ${ref("covid19_open_data")}
WHERE
  country_code = "JP"
  AND location_key = "JP_13" -- 東京はJP_13
GROUP BY
  date
